config/routes.rb
JqmApp::Application.routes.draw do
  
  resources :bookmarks
  
  resources :posts
  
  root :to => "posts#index"
  
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.xml
  def index
    @bookmarks = Bookmark.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.xml
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.xml
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.xml
  def create
    @bookmark = Bookmark.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully created.') }
        format.xml  { render :xml => @bookmark, :status => :created, :location => @bookmark }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.xml
  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.xml
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to(bookmarks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "jquery_mobile"
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/bookmarks/_form.html.haml
= simple_form_for(@bookmark) do |f|
  - if @bookmark.errors.any?
    #error_explanation
      %h2 #{pluralize(@bookmark.errors.count, "error")} prohibited this bookmark from being saved:

      %ul
        - @bookmark.errors.full_messages.each do |msg|
          %li= msg

  .inputs
    = f.input :title
    = f.input :body
    
  .actions
    = f.button :submit

app/views/bookmarks/edit.html.haml
%h1 Editing bookmark

= render 'form'

= link_to "Cancel", :back

app/views/bookmarks/index.html.haml
%h1 Listing bookmarks

%table
  %thead
    %tr
      %th Title
      %th Body
      %th{ :colspan => 3 }
  
  %tbody
    - for bookmark in @bookmarks
      %tr{ :class => cycle(:odd, :even) }
        %td= bookmark.title
        %td= bookmark.body
        %td= link_to 'Show', bookmark
        %td= link_to 'Edit', edit_bookmark_path(bookmark)
        %td= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete

%br
= link_to 'New bookmark', new_bookmark_path

app/views/bookmarks/new.html.haml
%h1 New bookmark

= render 'form'

= link_to 'Back', bookmarks_path

app/views/bookmarks/show.html.haml
%p
  %strong Title:
  = @bookmark.title
%p
  %strong Body:
  = @bookmark.body

= link_to 'Edit', edit_bookmark_path(@bookmark)

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title JqmApp
    = stylesheet_link_tag "scaffold"
    = javascript_include_tag :defaults
    = csrf_meta_tag
  
  %body
    = yield

app/views/layouts/jquery_mobile.html.haml
!!!5
%html
  %head
    %title JqmApp
    = stylesheet_link_tag "jquery.mobile"
    = javascript_include_tag :defaults
    = javascript_include_tag "jquery.mobile-1.0a3.min"
    = csrf_meta_tag
  
  %body
    
    %div{:data => {:role => "page", :theme => "b"}}
      %div{:data => {:role => 'header', :position => 'fixed'}}
        = yield(:header)
        = link_to 'Home', posts_url, :class => "ui-btn-right", :rel => "external", 'data-icon' => 'home'
        = link_to 'New post', new_post_url, :class => "ui-btn-left", :rel => "external", 'data-icon' => 'plus'
      
      %div{:data => {:role => 'content'}}
        = yield
      
      %div.ui-bar{:data => {:role => 'footer', :position => 'fixed'}}
        = yield(:footer)
        = link_to "About", "http://devteam.sales-lentz.lu",:class => "ui-btn-right", :target => "_blank", 'data-icon' => 'info'

app/views/posts/_form.html.haml
= simple_form_for(@post) do |form| 
  .inputs
    = form.input :title
    = form.input :body
    
  .actions
    = form.button :submit, 'data-icon' => 'check'

app/views/posts/edit.html.haml
- content_for :header do
  %h1 Edit post

- content_for :footer do
  = link_to "Cancel", post_path(@post), :rel => "external", 'data-icon' => 'delete', 'data-role' => 'button'


= render 'form'

app/views/posts/index.html.haml
- content_for :header do
  %h1 Listing posts

- content_for :footer do
  = link_to 'New post', new_post_path, 'data-icon' => 'plus', 'data-role' => 'button'


%ul{:data => {:role => "listview"}}
  - @posts.each do |post|
    %li
      = link_to post.title, post
      = link_to 'edit post', edit_post_path(post), 'data-icon' => 'gear'
      

app/views/posts/new.html.haml
- content_for :header do
  %h1 New post

- content_for :footer do
  = link_to "Cancel", posts_path, :rel => "external", 'data-icon' => 'delete', 'data-role' => 'button'


= render 'form'

app/views/posts/show.html.haml
- content_for :header do
  %h1= @post.title

- content_for :footer do
  = link_to 'Edit', edit_post_path(@post), 'data-icon' => 'gear', 'data-role' => 'button'
  = link_to 'Delete', post_path(@post), :method => :delete, :confirm => "realy delete?", 'data-icon' => 'delete'


%h1= @post.title
%p= @post.body